import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { Scene } from '../schemas/sceneSchema';

// Vite raw imports for the actual source files we want to bundle
import bgRaw from '../components/remotion/BackgroundRenderer.tsx?raw';
import camRaw from '../components/remotion/CameraRig.tsx?raw';
import ktypeRaw from '../components/remotion/KineticTypography.tsx?raw';
import transRaw from '../components/remotion/TransitionOverlay.tsx?raw';
import chartRaw from '../visuals/ChartVisual.tsx?raw';
import titleRaw from '../visuals/TitleVisual.tsx?raw';
import scriptSchemaRaw from '../schemas/scriptSchema.ts?raw';
import sceneSchemaRaw from '../schemas/sceneSchema.ts?raw';
import genCompRaw from '../compositions/GeneratedComposition.tsx?raw';

export const exportProject = async (scenes: Scene[]) => {
  const zip = new JSZip();
  const totalDurationFrames = scenes.length > 0 ? scenes[scenes.length - 1].endTime : 30;

  zip.file("scene_plan.json", JSON.stringify({ scenes }, null, 2));

  // Core component files
  zip.folder("src/components/remotion")?.file("BackgroundRenderer.tsx", bgRaw);
  zip.folder("src/components/remotion")?.file("CameraRig.tsx", camRaw);
  zip.folder("src/components/remotion")?.file("KineticTypography.tsx", ktypeRaw);
  zip.folder("src/components/remotion")?.file("TransitionOverlay.tsx", transRaw);
  zip.folder("src/visuals")?.file("ChartVisual.tsx", chartRaw);
  zip.folder("src/visuals")?.file("TitleVisual.tsx", titleRaw);
  zip.folder("src/schemas")?.file("scriptSchema.ts", scriptSchemaRaw);
  zip.folder("src/schemas")?.file("sceneSchema.ts", sceneSchemaRaw);
  zip.folder("src/compositions")?.file("GeneratedComposition.tsx", genCompRaw);

  // Setup files
  zip.file("remotion.config.ts", `
import { Config } from '@remotion/cli/config';
Config.setVideoImageFormat('jpeg');
  `.trim());

  zip.file("src/index.ts", "import { registerRoot } from 'remotion';\nimport { RemotionRoot } from './Root';\n\nregisterRoot(RemotionRoot);");
  zip.file("src/Root.tsx", `
import { Composition } from 'remotion';
import { GeneratedComposition } from './compositions/GeneratedComposition';
import planData from '../scene_plan.json';

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="CinematicTemplate"
        component={GeneratedComposition}
        durationInFrames={${totalDurationFrames}}
        fps={30}
        width={1920}
        height={1080}
        defaultProps={{
          scenes: planData.scenes as any
        }}
      />
    </>
  );
};
  `.trim());

  zip.file("package.json", JSON.stringify({
    name: "cinematic-template",
    version: "1.0.0",
    scripts: {
      "start": "remotion preview src/index.ts",
      "build": "remotion render src/index.ts CinematicTemplate out.mp4"
    },
    dependencies: {
      "remotion": "^4.0.534",
      "react": "^18.0.0",
      "react-dom": "^18.0.0",
      "zod": "^3.23.0"
    },
    devDependencies: {
      "@remotion/cli": "^4.0.534",
      "@types/react": "^18.0.0",
      "@types/react-dom": "^18.0.0",
      "typescript": "^5.0.0"
    }
  }, null, 2));

  zip.file("README.md", `
# Generated Remotion Cinematic Template

This project was automatically generated by the Remotion Cinematic Template Intelligence Studio.

## Getting Started

1. Install dependencies:
   \`npm install\`

2. Preview the video in your browser:
   \`npm start\`

3. Render the final MP4 video:
   \`npm run build\`
  `.trim());

  const content = await zip.generateAsync({ type: "blob" });
  saveAs(content, "remotion_cinematic_template.zip");
};
